name: CI-NodeJS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  NodeJS:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: NodeJS
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20.x'

      - name: Dependencies
        run: npm install

      - name: Unit Tests
        run: npm test -- --coverage

      - name: Coverage Rapport
        uses: actions/upload-artifact@v5
        with:
          name: results
          path: coverage/
        
  code-quality:
    runs-on: ubuntu-latest
    needs: NodeJS

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: NodeJS
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20.x'

      - name: Dependencies
        run: npm install

      - name: ESLint 
        run: npm run lint

      # - name: Prettier Check
      #   run: npm run format:check --write

      - name: Security audit
        run: npm audit --audit-level=moderate
