name: CI-NodeJS

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: NodeJS
        uses: actions/setup-node@v4.4.0
        with:
            node-version: '20.x'
      - name: Dependencies
        run: npm install

      - name: Unit Tests
        run: npm test -- --coverage

      - name: Coverage Rapport
        # uses: mridang/action-test-reporter@v1
        # with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          # coverage-file: ./coverage/clover.xml
          # working-directory: ./
        uses: actions/upload-artifact@v5
        with:
          name: results
          path: coverage/

        

