name: Complete Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '15'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the code
        run: npm run build

      - name: Bundle code into zip
        run: |
          mkdir -p bundle
          cp -r . bundle/
          zip -r app_bundle.zip bundle node_modules

      - name: Test the code
        run: |
          npm test -- --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_DIR: ./test-results
          JEST_JUNIT_OUTPUT_NAME: junit.xml

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./test-results/junit.xml
