name: Complete Example

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20.x'
          cache: npm
          
      - name: Build and test
        run: |
          npm install
          npm run build --if-present
          npm test

      - name: Make zip
        uses: actions/upload-artifact@v5
        with:
          name: my-apps
          path: .
            
      - name: Make report
        uses: actions/upload-artifact@v5
        with:
          name: code-coverage-report
          path: output/test/code-coverage.htm
      
